apiVersion: v1
kind: Service
metadata:
  name: postgresdb
  labels:
    app: postgres
spec:
  type: NodePort
  selector:
    app: postgresdb
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30432
      name: postgresdb-port
      protocol: TCP
