apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_DB: hams_data
  POSTGRES_USER: hams_data
  POSTGRES_PASSWORD: hams_data
  DATABASE_URL: postgresql://hams_data:hams_data@postgres:5432/hams_data
