management:
  endpoints:
    enabled-by-default: false
server:
  name: security-server
  port: 8082
  datasource:
    initialization-mode: always
  error:
    include-stacktrace: always
spring:
  application:
    name: security-server
  sql:
    init:
      continue-on-error: true
