apiVersion: v1
kind: Service
metadata:
  name: kafka-broker
  labels:
    name: kafka-broker
spec:
  type: LoadBalancer
  selector:
    app: kafka-broker
  ports:
    - name: kafka-broker-port
      port: 9092
      protocol: TCP
    - name: controller
      port: 9093
      targetPort: 9093
