apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  labels:
    app: kafka-broker
spec:
  type: ClusterIP
  clusterIP: None  # headless
  selector:
    app: kafka-broker
  ports:
    - name: kafka-broker
      port: 9092
      targetPort: 9092
    - name: controller
      port: 9093
      targetPort: 9093