apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  labels:
    app: kafka-ui
spec:
  type: LoadBalancer
  selector:
    app: kafka-ui
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
