#!/bin/bash

# turn on bash's job control
set -m

cd kafka-servers || exit

# start zookeeper
./start-zookeeper &

# sleep to wait for zookeeper to start
sleep 20

# start kafka servers
./start-kafka-server &

# sleep again to wait for kafka servers to start
sleep 10

cd ../kafdrop || exit

mvn clean package

# start kafdrop
./start-kafdrop &

cd ../

# bring first process (zookeeper) to foreground
fg %1
